### ISSUE TITLE
No module named 'sql.sql'; 'sql' is not a package

### ISSUE THREAD

**Issue by laminda** [andreyru02/telegram-grabber#10]
Hello! When installing, I get the following error, what could be the problem? 

```
"./bot_grabber.py", line 7, in <module>
from sql.sql import SQL
ModuleNotFoundError: No module named 'sql.sql'; 'sql' is not a package
"
```

**Comment by andreyru02** [comment]
Запускаешь на windows? Если да, то скопируй файл sql.py из папки sql в папку python_bot и сделай соответствующий импорт.
