### ISSUE TITLE
Не парсит посты 

### ISSUE THREAD

**Issue by laminda** [andreyru02/telegram-grabber#11]
Настроил бота, добавил канал донор, создал канал для модерации, и основной. Сделал все по инструкции, но бот не пересылает посты в канал модерации. Можете  пожалуйста сделать более подробное описание, как он должен работать ?

**Comment by andreyru02** [comment]
С аккаунта, на котором получал API_ID и API_HASH подписан на аккаунты, с которых нужно пересылать посты?
