### ISSUE TITLE
Работает не всё

### ISSUE THREAD

**Issue by Midoritotoro** [andreyru02/telegram-grabber#13]
Работает только часть функций: добавление доноров, модеров и основных каналов, список каналов доноров. А копирование из канала донора и пересылка на канал модер не работает

**Comment by andreyru02** [comment]
С описанными проблемами часто встречаются пользователи.
Возможные причины:
1) Установлена не та версия pyrogram.
2) Не подписаны на каналы доноры с аккаунта, которого получали API ID и API_HASH.
3) Бот запускается на windows (бот использует команды linux для перезапуска основного бота, для применения изменений в БД).
4) Каналы (доноры, модер, основной) приватные.
5) Не понимание функции бота. Бот копирует только новые посты, которые создались во время работы бота.
6) Не правильно сохраненные названия каналов для доноров, модера, основного канала (с "https" и тд).

_**Данный бот уже не поддерживается.**_
Экспериментируйте, читайте логи/трейсбек.
