### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by STARTSPr0** [andreyru02/telegram-grabber#7]
Знаю что задолбал тебя, но твой скрипт мне интересен) 
Есть возможность не пересылки сообщений в основной канал, а именно копирование сообщения с текстом, картинкой, видосом и т.д.

**Comment by andreyru02** [comment]
> Знаю что задолбал тебя, но твой скрипт мне интересен)
> Есть возможность не пересылки сообщений в основной канал, а именно копирование сообщения с текстом, картинкой, видосом и т.д.

Что бы не было видно, откуда сделал репост?

**Comment by STARTSPr0** [comment]
> Что бы не было видно, откуда сделал репост?

Да, без репоста

**Comment by andreyru02** [comment]
> > Что бы не было видно, откуда сделал репост?
> 
> Да, без репоста

Для этого и нужен as_copy=True

**Comment by STARTSPr0** [comment]
> > > Что бы не было видно, откуда сделал репост?
> > 
> > 
> > Да, без репоста
> 
> Для этого и нужен as_copy=True

Ну ё-мое, буду пробовать тогда удалять последнюю версию и ставить старую. Первоначально канешь пороюсь в апи, может есть какой метод

**Comment by andreyru02** [comment]
> > > > Что бы не было видно, откуда сделал репост?
> > > 
> > > 
> > > Да, без репоста
> > 
> > 
> > Для этого и нужен as_copy=True
> 
> Ну ё-мое, буду пробовать тогда удалять последнюю версию и ставить старую. Первоначально канешь пороюсь в апи, может есть какой метод

Поэтому и я оставил требованием старую версию.)

**Comment by andreyru02** [comment]
Пиши если что в телеграм @andrey_andrey01
