### ISSUE TITLE
No API Key found

### ISSUE THREAD

**Issue by nikitas244** [andreyru02/telegram-grabber#8]
Здравствуй. Добавлял всё по пункту №3, делал всё как в шаге №1 и №2, но, почему-то, вылезает ошибка "AttributeError: No API Key found. More info: https://docs.pyrogram.org/intro/setup". Что может быть не так? Все API ID прописаны...

**Comment by andreyru02** [comment]
> Здравствуй. Добавлял всё по пункту №3, делал всё как в шаге №1 и №2, но, почему-то, вылезает ошибка "AttributeError: No API Key found. More info: https://docs.pyrogram.org/intro/setup". Что может быть не так? Все API ID прописаны...

Привет.
Переменные виртуального окружения как задаешь?
Можешь сделать проще.
В файле bot_grabber.py, на строчке 9-10, где os.getenv('API_ID') пропиши свой API ID и где os.getenv('API_HASH') тоже самое.
В файле bot_restart.py, на строчке 18-19 тоже самое, что и описано сверху. Вместо os.getenv - свои данные.
