### ISSUE TITLE
Ошибка  (Task exception was never retrieved future)

### ISSUE THREAD

**Issue by vladick-228** [andreyru02/telegram-grabber#9]
Пытаюсь запустить на винде...
Вылазит при добавлении донора, модера и канала
сама ошибка 
`Task exception was never retrieved
future: <Task finished name='Task-27' coro=<Dispatcher._process_polling_updates() done, defined at C:\Users\polev\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py:401> exception=FileNotFoundError(2, 'Не удается найти указанный файл', None, 2, None)>
Traceback (most recent call last):
  File "C:\Users\polev\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 409, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\Users\polev\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\Users\polev\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\polev\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 286, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "C:\Users\polev\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\polev\Desktop\telegram-grabber-main1\restart_bot\bot_restart.py", line 115, in action
    await bot.send_message(USER_ID, restart_session.command_execution())
  File "C:\Users\polev\Desktop\telegram-grabber-main1\restart_bot\restart.py", line 6, in command_execution
    subprocess.run(['pkill', '-f', 'bot_grabber.py'])
  File "C:\Users\polev\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\polev\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\polev\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Не удается найти указанный файл`
 Код
`from pyrogram import Client, filters
from datetime import datetime
import os
import sys
base_dir = os.path.abspath(os.path.join(os.path.dirname('bot_grabber.py'), '..'))
sys.path.append(base_dir)
from sql.sql import SQL

api_id = '0'
api_hash = '0'

app = Client('bot_python', api_id, api_hash)
bd = SQL('../bd.db')

@app.on_message(filters.chat(bd.get_donor()))
def get_post(client, message):
    username = message.chat.username
    message_id = message.message_id

    if not bd.message_id_exists(username, message_id):
        bd.add_message_id(username, message_id)
        # получение последнего ROWID
        for a in bd.get_last_rowid():
            last_id = a[0]

        # перессылка поста на модерку
        message.forward(bd.get_moder())
        client.send_message(bd.get_moder(), last_id)

@app.on_message(filters.chat(bd.get_moder()))
def send_post(client, message):
    # получаем запись в таблице
    for item in bd.get_data_in_table(message):
        username = item[0]
        msg_id = item[1]

    send = app.get_messages(username, msg_id)
    # send.forward(bd.get_channel(), as_copy=True)
    send.copy(bd.get_channel())

if __name__ == '__main__':
    print(datetime.today().strftime(f'%H:%M:%S | Bot Telegram-Grabber launched.'))
    app.run()
from aiogram import Bot, Dispatcher, types
from aiogram.contrib.fsm_storage.memory import MemoryStorage
from aiogram.dispatcher import FSMContext
from aiogram.dispatcher.filters import Text
from aiogram.dispatcher.filters.state import State, StatesGroup
from aiogram.types import InlineKeyboardMarkup, InlineKeyboardButton
from aiogram.utils import executor
from datetime import datetime
from restart import Commands
import os
import sys
import asyncio
import time
base_dir = os.path.abspath(os.path.join(os.path.dirname('bot_grabber.py'), '..'))
sys.path.append(base_dir)
from sql.sql import SQL

restart_session = Commands()

TOKEN = '0'
USER_ID = '0'

db = SQL('../bd.db')
bot = Bot(token=TOKEN)
storage = MemoryStorage()
dp = Dispatcher(bot, storage=storage)

keyboard = InlineKeyboardMarkup(row_width=3)
donor_k = InlineKeyboardButton(text='Донор', callback_data="donor")
moder_k = InlineKeyboardButton(text='Модер', callback_data="moder")
channel_k = InlineKeyboardButton(text='Канал', callback_data="channel")
print_donor_list = InlineKeyboardButton(text='Вывести список доноров', callback_data='donor_list')
keyboard.add(donor_k, moder_k, channel_k, print_donor_list)

donor_keyboard = InlineKeyboardMarkup(row_width=2)
donor_add = InlineKeyboardButton(text='Добавить', callback_data="add_donor")
donor_delete = InlineKeyboardButton(text='Удалить', callback_data="delete_donor")
donor_keyboard.add(donor_add, donor_delete)

moder_keyboard = InlineKeyboardMarkup(row_width=2)
moder_add = InlineKeyboardButton(text='Добавить', callback_data="add_moder")
moder_delete = InlineKeyboardButton(text='Удалить', callback_data="delete_moder")
moder_keyboard.add(moder_add, moder_delete)

channel_keyboard = InlineKeyboardMarkup(row_width=2)
channel_add = InlineKeyboardButton(text='Добавить', callback_data="add_channel")
channel_delete = InlineKeyboardButton(text='Удалить', callback_data="delete_channel")
channel_keyboard.add(channel_add, channel_delete)

class Form(StatesGroup):
    name = State()

@dp.message_handler(commands=['start'])
async def cmd_start(message: types.Message):
    if message.from_user.id == int(USER_ID):
        await bot.send_message(USER_ID, 'Управление базой данных.', reply_markup=keyboard)
    else:
        await bot.send_message(message.from_user.id, 'Недостаточно привелегий для управления!')

@dp.message_handler(state='*', commands='cancel')
@dp.message_handler(Text(equals='отмена', ignore_case=True), state='*')
async def cancel_handler(message: types.Message, state: FSMContext):
    current_state = await state.get_state()
    if current_state is None:
        return

    await state.finish()
    await message.reply('ОК')

# Сюда приходит ответ с именем
@dp.message_handler(state=Form.name)
async def process_name(message: types.Message, state: FSMContext):
    await Form.name.set()
    async with state.proxy() as data:
        data['name'] = message.text
    await Form.next()
    if check_name == 'donor':
        await bot.send_message(USER_ID,
                               'Выберите действие:', reply_markup=donor_keyboard)

    elif check_name == 'moder':
        await bot.send_message(USER_ID,
                               'Выберите действие:', reply_markup=moder_keyboard)

    elif check_name == 'channel':
        await bot.send_message(USER_ID,
                               'Выберите действие:', reply_markup=channel_keyboard)

@dp.callback_query_handler(state='*')
async def action(call: types.CallbackQuery, state: FSMContext):
    global check_name
    check_name = ''
    if call.data == 'donor':
        await Form.next()
        check_name = call.data
        await bot.send_message(USER_ID, 'Введите название:')

    elif call.data == 'moder':
        await Form.next()
        check_name = call.data
        await bot.send_message(USER_ID, 'Введите название:')

    elif call.data == 'channel':
        await Form.next()
        check_name = call.data
        await bot.send_message(USER_ID, 'Введите название:')

    elif call.data == 'add_donor':
        async with state.proxy() as data:
            await bot.send_message(
                USER_ID, db.add_donor(data['name']))
            await bot.send_message(USER_ID, restart_session.command_execution())

    elif call.data == 'delete_donor':
        async with state.proxy() as data:
            await bot.send_message(
                USER_ID, db.delete_donor(data['name']))
            await bot.send_message(USER_ID, restart_session.command_execution())

    elif call.data == 'add_moder':
        async with state.proxy() as data:
            await bot.send_message(
                USER_ID, db.add_moder(data['name']))
            await bot.send_message(USER_ID, restart_session.command_execution())

    elif call.data == 'delete_moder':
        async with state.proxy() as data:
            await bot.send_message(
                USER_ID, db.delete_moder(data['name']))
            await bot.send_message(USER_ID, restart_session.command_execution())

    elif call.data == 'add_channel':
        async with state.proxy() as data:
            await bot.send_message(
                USER_ID, db.add_channel(data['name']))
            await bot.send_message(USER_ID, restart_session.command_execution())

    elif call.data == 'delete_channel':
        async with state.proxy() as data:
            await bot.send_message(
                USER_ID, db.delete_channel(data['name']))
            await bot.send_message(USER_ID, restart_session.command_execution())

    elif call.data == 'donor_list':
        await bot.send_message(
            USER_ID, db.print_donor())

    # await state.finish()

if __name__ == '__main__':
    print(datetime.today().strftime(f'%H:%M:%S | Bot Restart_Telegram launched.'))
    executor.start_polling(dp, skip_updates=True)
import subprocess

class Commands:
    def command_execution(self):
        subprocess.run(['taskkill', '-f', 'bot_grabber.py'])
        subprocess.Popen(['start /min', 'python', '-u', '../python_bot/bot_grabber.py', &])
        return 'Выполнен рестарт `сессии.'`

**Comment by andreyru02** [comment]
Бот для добавления  донора, модера и канала работает только на Linux, так как используются команды перезапуска процесса Linux. О чем и написано в инструкции по запуску Readme.
Ты можешь либо руками заполнить базу используя SQLiteStudio, либо арендовать VDS сервер на Linux.
Те, команды, которые ты изменил в классе Commands, возможно нужно указывать абсолютный путь до файл (где subprocess.Popen(['start /min', 'python', '-u', '../python_bot/bot_grabber.py', &]))
Если есть вопросы, можешь писать в телеграм @andrey_andrey01.
